# -*- coding: utf-8 -*-
"""01_RDD_08312026.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5c_ZeqjN90Qk6Sgs2bXU0U6cT1Exbae
"""

!pip install pyspark

from pyspark import SparkContext

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("01_RDD_08312026").getOrCreate()

sc=spark.sparkContext

#1Create an RDD from the dataset and multiply every number by 2.
rdd=sc.parallelize([5, 10, 15, 20, 25, 30])
print(type(rdd))
rdd=rdd.map(lambda x:x*2)
rdd.collect()

#2Find all numbers greater than 5.
num=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
rdd=sc.parallelize(num)
rdd1=rdd.filter(lambda x: x>5)
rdd1.collect()

#3.Add 100 to every number.
num=[10, 20, 30, 40, 50]
rdd=sc.parallelize(num)
rdd1=rdd.map(lambda x: x+100)
print(rdd1.collect())

#4.Find the square of every number.
num=[2, 4, 6, 8, 10]
rdd=sc.parallelize(num)
rdd1=rdd.map(lambda x: x**2)
rdd1.collect()

#5.Find the count of numbers greater than 20.
num=[10, 15, 20, 25, 30, 35, 40]
count=0
rdd=sc.parallelize(num)
rdd1=rdd.filter(lambda x: x>=20)
print(rdd1.collect())
print(rdd1.count())

#6.Calculate the sum of all numbers.
num=[10, 20, 30, 40, 50]
rdd=sc.parallelize(num)
print(rdd.collect())
print(rdd.sum())

#7.Find the maximum value.
num=[10, 50, 20, 90, 40, 70]
value=sc.parallelize(num)
value.max()

#8.Find the minimum value.
num=[10, 50, 20, 90, 40, 70]
value=sc.parallelize(num)
# small=value.reduce(lambda x,y:min(x,y))
# print(small)
value.reduce(lambda x,y:min(x,y))

#9.Calculate the product of all numbers.
num=[1, 2, 3, 4, 5]
product=sc.parallelize(num)
product.reduce(lambda x,y:x*y)

#10.Calculate the total after adding an initial value of 100.
num=[10, 20, 30, 40, 50]
rdd=sc.parallelize(num)
total=rdd.reduce(lambda x,y:x+y)+100
print(total)

num = [10, 20, 30, 40, 50]

value = sc.parallelize(num)

rdd = value.zipWithIndex().map(
    lambda x: x[0] + 100 if x[1] == 0 else x[0]
)

print(rdd.sum())

Employee_Data=[
 (101, "Alice", "IT", 80000),
 (102, "Bob", "HR", 60000),
 (103, "Charlie", "IT", 90000),
 (104, "David", "Finance", 75000),
 (105, "Eva", "HR", 65000),
 (106, "Frank", "Finance", 85000),
 (107, "Grace", "IT", 95000),
 (108, "Henry", "Sales", 70000),
 (109, "Ivy", "Sales", 72000),
 (110, "Jack", "IT", 88000) ]

#11.Find all employees who work in the IT department.
data=sc.parallelize(Employee_Data)
find=data.filter(lambda x:x[2]=="IT").map(lambda x:x[1])
print(find.collect())

#12.Find employees earning more than 80000.
find=data.filter(lambda x :x[3]>80000).map(lambda x: x[1])
find.collect()

#13.Find the names and salaries of all employees.
find=data.map(lambda x:(x[1],x[3]))
find.collect()

#14.Increase every employee's salary by 10%.
find=data.map(lambda x: (x[1],round(x[3]*1.10)))
find.collect()
for i,j in find.collect():
  print(f"{i}->{j}")

#15.Find the names of employees earning between 70000 and 90000 inclusive.
find=data.filter(lambda x:x[3]>70000 and x[3]<=90000).map(lambda x:x[1])
find.collect()

#16.Find IT employees whose salary is greater than 85000.
data=sc.parallelize(Employee_Data)
value=data.filter(lambda x: x[2]=="IT" and x[3]>85000).map(lambda x :x[1])
value.collect()

#17.Find the total number of employees.
value=data.map(lambda x :x[1])
value.collect()
value.count()

"""**Dataset 3**"""

Sentences=[
 "spark is fast",
 "spark is powerful",
 "hadoop is distributed",
 "spark and hadoop are popular",
 "kafka is streaming"
]

#118.Convert all sentences into individual words.
words=sc.parallelize(Sentences)
word=words.flatMap(lambda x:x.split())
word.collect()

#19.Find the total number of words.
words=sc.parallelize(Sentences)
word=words.flatMap(lambda x:x.split())
word.collect()
word.count()

#20.Find all words having more than 4 characters.
words=sc.parallelize(Sentences)
# word=words.flatMap(lambda x:x.split()).filter(lambda x:len(x)>4)
# print(word.collect())
word=words.flatMap(lambda x:x.split())
for i in word.collect():
  if len(i)>4:
    print(i)

#21.Convert every word into uppercase.
words=sc.parallelize(Sentences)
word=words.map(lambda x:x.upper())
word.collect()

#22.Find the number of unique words.
Sentences=[
 "spark is fast",
 "spark is powerful",
 "hadoop is distributed",
 "spark and hadoop are popular",
 "kafka is streaming"
]
words=sc.parallelize(Sentences)
word=words.flatMap(lambda x:x.split())
unique_words=word.distinct()
unique_words.count()

"""**Dataset 4**"""

Word_Count=[
 "spark is fast",
 "spark is powerful",
 "spark is easy",
 "hadoop is distributed",
 "spark is fast"
]

#23.Calculate the frequency of every word.
Words=sc.parallelize(Word_Count)
word=Words.flatMap(lambda x:x.split())
frequency={}
for i in word.collect():
  if i in frequency:
    frequency[i]+=1
  else:
    frequency[i]=1


for i,j in frequency.items():
  print(f"{i}->{j}")

Words = sc.parallelize(Word_Count)

word = Words.flatMap(lambda x: x.split())

frequency = word.map(lambda x: (x, 1)) .reduceByKey(lambda a, b: a + b)

for i,j in frequency.collect():
  print(i,"->",j)

#24.Find the most frequently occurring word.
word=Words.flatMap(lambda x:x.split())
frequency={}
for i in word.collect():
  if i in frequency:
    frequency[i]+=1
  else:
    frequency[i]=1

high=0
word=0
for i,j in frequency.items():
  if j >high:
    high=j
    word=i
print(word,"->",high)

word=Words.flatMap(lambda x:x.split())
frequency=word.map(lambda x:(x,1)).reduceByKey(lambda a,b:a+b)
frequency.collect()
high=0
word=0
for i,j in frequency.collect():
  if j>high:
    word=i
    high=j
print(i,"->",j)

#25.Find all words that occur more than once.
word=Words.flatMap(lambda x:x.split())
frequency=word.map(lambda x:(x,1)).reduceByKey(lambda a,b:a+b)
frequency.collect()
for i,j in frequency.collect():
  if j>1:
    print(i,"->",j)

word=Words.flatMap(lambda x:x.split())
frequency={}
for i in word.collect():
  if i in frequency:
    frequency[i]+=1
  else:
    frequency[i]=1
for i,j in frequency.items():
  if j >1:
    print(i,"->",j)

#26.Calculate the total number of words.
word=Words.flatMap(lambda x:x.split())
word.count()

"""**Dataset 5**"""

Department_Salaries=[
 ("IT", 80000),
 ("HR", 60000),
 ("IT", 90000),
 ("Finance", 75000),
 ("HR", 65000),
 ("Finance", 85000),
 ("IT", 95000),
 ("Sales", 70000),
 ("Sales", 72000),
 ("IT", 88000)
]

#27.Group all salaries by department.
department=sc.parallelize(Department_Salaries)
department.collect()
departments=department.groupByKey()
for i,j in departments.collect():
  print(i,"->",list(j))

#28.Calculate the total salary for every department.
department=sc.parallelize(Department_Salaries)
departments=department.groupByKey()
for i,j in departments.collect():
  print(i,"->",sum(j))

#29.Calculate the average salary for every department.
department=sc.parallelize(Department_Salaries)
departments=department.groupByKey()
for i,j in departments.collect():
  average=sum(j)/len(j)
  print(i,"->",round(average))

#30.Find the highest salary in every department.
department=sc.parallelize(Department_Salaries)
department.collect()
departments=department.groupByKey()
for i,j in departments.collect():
  print(i,"->",max(j))

#31.Find the department having the highest total salary
department=sc.parallelize(Department_Salaries)
departments=department.groupByKey()
high=0
depart=""
for i,j in departments.collect():
  # print(i,"->",sum(j))
  if sum(j)>high:
    high=sum(j)
    depart=i
print(depart,high)

"""**Dataset 6**"""

Sales=[
 ("Laptop", 2, 50000),
 ("Mobile", 5, 20000),
 ("Laptop", 1, 50000),
 ("Tablet", 3, 15000),
 ("Mobile", 2, 20000),
 ("Laptop", 4, 50000),
 ("Tablet", 2, 15000),
 ("Mobile", 3, 20000)
]

#32.Calculate the revenue for every transaction
sale=sc.parallelize(Sales)
revenue=sale.map(lambda x:(x[0],x[1]*x[2]))
revenue.collect()

#33.Calculate total revenue for every product.
sale=sc.parallelize(Sales)
sale.collect()
revenue=sale.map(lambda x:(x[0],x[1]*x[2]))
revenue.collect()
total_rev=revenue.groupByKey()
for i,j in total_rev.collect():
  print(i,"->",sum(j))

#34.Calculate the total quantity sold for every product.
sale=sc.parallelize(Sales)
sale.collect()
total=sale.map(lambda x: (x[0],x[1]))
total.collect()
total_quant=total.groupByKey()
for i,j in total_quant.collect():
  print(i,"->",sum(j))

#35.Find the product with the highest total revenue.
sale=sc.parallelize(Sales)
sale.collect()
revenue=sale.map(lambda x:(x[0],x[1]*x[2]))
revenue.collect()
total_rev=revenue.groupByKey()
total_rev.collect()
high=0
item=""
for i,j in total_rev.collect():
  # print(i,"->",sum(j))
  if sum(j)>high:
    high=sum(j)
    item=i
print(item,"->",high)

#36.Find products whose total revenue is greater than 100000.
sale=sc.parallelize(Sales)
revenue=sale.map(lambda x: (x[0],x[1]*x[2]))
revenue.collect()
total_rev=revenue.groupByKey()
for i,j in total_rev.collect():
  if sum(j)>100000:
    print(i,"->",sum(j))

"""**Dataset 7**"""

Customer_Transactions=[
 ("C001", 1000),
 ("C002", 500),
 ("C001", 700),
 ("C003", 1200),
 ("C002", 800),
 ("C001", 300),
 ("C003", 400),
 ("C004", 1500),
 ("C002", 200)
]

#37.Group all transaction amounts by customer.
Transaction=sc.parallelize(Customer_Transactions)
total_Trans=Transaction.groupByKey()
for i,j in sorted(total_Trans.collect()):
  print((i),"->",list(j))

#38.Calculate the total transaction amount for each customer.
Transaction=sc.parallelize(Customer_Transactions)
total_Trans=Transaction.groupByKey()
for i,j in sorted(total_Trans.collect()):
  print(i,"->",sum(j))

#39.Find the customer with the highest total transaction amount.
Transaction=sc.parallelize(Customer_Transactions)
total_Trans=Transaction.groupByKey()
high=0
word=""
for i,j in sorted(total_Trans.collect()):
  # print(i,"->",sum(j))
  if sum(j)>high:
    high=sum(j)
    word=i
print(word,"->",high)

#40.Find customers whose total transaction amount is greater than 1500.
Transaction=sc.parallelize(Customer_Transactions)
total_Trans=Transaction.groupByKey()
for i,j in sorted(total_Trans.collect()):
  # print(i,"->",sum(j))
  if sum(j)>1500:
    print(i,"->",sum(j))

"""**Dataset 8- Log File**"""

with open("application.log","w") as f:
      f.write('''INFO Application started
INFO Reading input file
ERROR Failed to read file
INFO Retrying operation
ERROR Connection timeout
WARN High memory usage
INFO Operation completed
ERROR Failed to write output
INFO Application stopped''')

# # read=sc.textfile(r"/content/application.log")
# # print(read.collect())
with open("/content/application.log","r") as f:
     file=f.read()
print(file)

#41.Read the file and display every line
rdd = sc.textFile("/content/application.log")
rdd.collect()

#42.Find all log entries containing ERROR.
rdd = sc.textFile("/content/application.log")
rdd.collect()
for i in rdd.collect():
  if i.startswith("ERROR"):
    print(i)

#43.Find the number of ERROR messages.
rdd = sc.textFile("/content/application.log")
rdd.collect()
count=0
for i in rdd.collect():
  if i.startswith("ERROR"):
    # print(i)
    count += 1
print(count)

#44.Calculate the number of messages for each log level.
rdd = sc.textFile("/content/application.log")
rdd.collect()
words=rdd.flatMap(lambda x: x.split())
words.collect()
frequency={}
for i in rdd.collect():
  message=i.split()[0]
  if message in frequency:
    frequency[message] +=1
  else:
    frequency[message]=1
print(frequency)

"""**Dataset 9- Numbers and Partitions**"""

#How many output part files will be generated if the RDD has 10 partitions and no partition reduction is performed?
rdd = sc.parallelize(range(1, 101), 10)
# rdd.coalesce(10).saveAsTextFile("output/number")
files = os.listdir("/content/output/number")
part_files = [f for f in files if f.startswith("part-")]

print(part_files)
print("Number of part files:", len(part_files))

#Save the numbers into the same output directory but make sure the data is written into only one partition before saving.
# 45.import shutil


# shutil.rmtree("/content/output/numbers", ignore_errors=True)

rdd = sc.parallelize(range(1, 101), 10)

# rdd.saveAsTextFile("/content/output/numbers")
import os

files = os.listdir("/content/output/numbers")

part_files = [f for f in files if f.startswith("part-")]

print(part_files)
print("Number of part files:", len(part_files))

#Create an RDD containing numbers from 1 to 1000 with 20 partitions. Reduce the number of partitions to 5 before saving
rdd = sc.parallelize(range(1, 1001), 20)

# rdd.coalesce(20).saveAsTextFile("/content/output/numbers1")
print("Before:",rdd.getNumPartitions() ,"Partitions" )

rdd=rdd.coalesce(5)
print("After:",rdd.getNumPartitions(),"Partitions")

#Create an RDD containing numbers from 1 to 10,000 with 20 partitions and save the data using only 2 output partitions.
rdd=sc.parallelize(range(1,10000),20)
rdd=rdd.coalesce(2)
print(rdd.getNumPartitions() ,"Part Files")

"""**Dataset 10**"""

Mixed_Business_Data=[
 ("O1", "Laptop", 2, 50000),
 ("O2", "Mobile", 5, 20000),
 ("O3", "Laptop", 1, 50000),
 ("O4", "Tablet", 3, 15000),
 ("O5", "Mobile", 2, 20000),
 ("O6", "Laptop", 4, 50000)
]

#49.Calculate the revenue of every order.
data=sc.parallelize(Mixed_Business_Data)
revenue=data.map(lambda x:(x[0],x[2]*x[3]))
revenue.collect()

"""50.Perform the following complete analysis:"""

#1.Calculate revenue for every order.
data=sc.parallelize(Mixed_Business_Data)
revenue=data.map(lambda x:(x[0],x[1],x[2]*x[3]))
revenue.collect()

#2.Keep only orders with revenue greater than 50000.
data=sc.parallelize(Mixed_Business_Data)
revenue=data.map(lambda x:(x[0],x[1],x[2]*x[3]))
revenue.collect()
greater=revenue.filter(lambda x:x[2]>50000)
greater.collect()

#3.Calculate total revenue for each product.
data=sc.parallelize(Mixed_Business_Data)
revenue=data.map(lambda x:(x[1],x[2]*x[3]))
revenue.collect()
value=revenue.groupByKey()
value.collect()
for i,j in value.collect():
  print(i,"->",sum(j))

#4.Find the product with the highest revenue.
data=sc.parallelize(Mixed_Business_Data)
revenue=data.map(lambda x:(x[1],x[2]*x[3]))
high=0
product=""
revenue.collect()
value=revenue.groupByKey()
value.collect()
for i,j in value.collect():
  # print(i,"->",sum(j))
  if sum(j)>high:
    high=sum(j)
    product=i
print(product,"->",high)

#5.Save the final result into a single output partition.
value = revenue.groupByKey()

final = value.map(lambda x: (x[0], sum(x[1])))

# final.coalesce(1).saveAsTextFile("/content/output/final_result")

import os

files = os.listdir("/content/output/final_result")
print(files)
part_files=[f for f in files if f.startswith("part-")]
print(part_files)
print("Number of part files:",len(part_files))

rdd=sc.parallelize(Mixed_Business_Data)
rdd.coalesce(1)
print(rdd.getNumPartitions(),"Part Files")

